// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rajiunschool.data;

#nullable disable

namespace rajiunschool.Migrations
{
    [DbContext(typeof(UmanagementContext))]
    [Migration("20250301165427_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rajiunschool.Models.booklist", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("availablepiece")
                        .HasColumnType("int");

                    b.Property<string>("details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Booklists");
                });

            modelBuilder.Entity("rajiunschool.Models.borrowbooks", b =>
                {
                    b.Property<int>("hudao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hudao"));

                    b.Property<string>("borrowedtime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("studentid")
                        .HasColumnType("int");

                    b.Property<string>("takenbacktime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("hudao");

                    b.ToTable("BorrowBooks");
                });

            modelBuilder.Entity("rajiunschool.Models.currentcoursemark", b =>
                {
                    b.Property<int>("hudao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hudao"));

                    b.Property<int>("attendance")
                        .HasColumnType("int");

                    b.Property<int>("ctmark")
                        .HasColumnType("int");

                    b.Property<int>("final")
                        .HasColumnType("int");

                    b.Property<int>("studentid")
                        .HasColumnType("int");

                    b.HasKey("hudao");

                    b.ToTable("CurrentCourseMarks");
                });

            modelBuilder.Entity("rajiunschool.Models.failedcoursemark", b =>
                {
                    b.Property<int>("hudao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hudao"));

                    b.Property<int>("attendance")
                        .HasColumnType("int");

                    b.Property<int>("ct")
                        .HasColumnType("int");

                    b.Property<int>("final")
                        .HasColumnType("int");

                    b.Property<int>("studentid")
                        .HasColumnType("int");

                    b.HasKey("hudao");

                    b.ToTable("FailedCourseMarks");
                });

            modelBuilder.Entity("rajiunschool.Models.paymentinfo", b =>
                {
                    b.Property<int>("hudao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hudao"));

                    b.Property<string>("paymentdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paymentmethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("session")
                        .HasColumnType("int");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("hudao");

                    b.ToTable("PaymentInfos");
                });

            modelBuilder.Entity("rajiunschool.Models.paymentviewforothers", b =>
                {
                    b.Property<int>("hudao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hudao"));

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<int>("bonus")
                        .HasColumnType("int");

                    b.Property<int>("employeeid")
                        .HasColumnType("int");

                    b.Property<int>("session")
                        .HasColumnType("int");

                    b.HasKey("hudao");

                    b.ToTable("PaymentViewForOthers");
                });

            modelBuilder.Entity("rajiunschool.Models.paymentviewforstudent", b =>
                {
                    b.Property<int>("hudao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hudao"));

                    b.Property<int>("addmissionfee")
                        .HasColumnType("int");

                    b.Property<int>("punishmentfee")
                        .HasColumnType("int");

                    b.Property<string>("session")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("studentid")
                        .HasColumnType("int");

                    b.Property<string>("transictionid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("transportationfee")
                        .HasColumnType("int");

                    b.Property<int>("tutionfee")
                        .HasColumnType("int");

                    b.HasKey("hudao");

                    b.ToTable("PaymentViewForStudents");
                });

            modelBuilder.Entity("rajiunschool.Models.paymentviewforteacher", b =>
                {
                    b.Property<int>("hudao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hudao"));

                    b.Property<int>("bonusfee")
                        .HasColumnType("int");

                    b.Property<int>("session")
                        .HasColumnType("int");

                    b.Property<int>("subject1")
                        .HasColumnType("int");

                    b.Property<int>("subject2")
                        .HasColumnType("int");

                    b.Property<int>("subject3")
                        .HasColumnType("int");

                    b.Property<int>("subject4")
                        .HasColumnType("int");

                    b.Property<int>("teacherid")
                        .HasColumnType("int");

                    b.HasKey("hudao");

                    b.ToTable("PaymentViewForTeachers");
                });

            modelBuilder.Entity("rajiunschool.Models.profileemployee", b =>
                {
                    b.Property<int>("hudao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hudao"));

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("age")
                        .HasColumnType("int");

                    b.Property<string>("bloodgroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("joindate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("profileid")
                        .HasColumnType("int");

                    b.Property<string>("sex")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("hudao");

                    b.ToTable("ProfileEmployees");
                });

            modelBuilder.Entity("rajiunschool.Models.profilestudent", b =>
                {
                    b.Property<int>("hudao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hudao"));

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("admittedsemester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("labclearancestatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("profileid")
                        .HasColumnType("int");

                    b.Property<string>("semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("hudao");

                    b.ToTable("ProfileStudents");
                });

            modelBuilder.Entity("rajiunschool.Models.session", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("rajiunschool.Models.studentnumbersheet", b =>
                {
                    b.Property<int>("hudao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hudao"));

                    b.Property<int>("mark1")
                        .HasColumnType("int");

                    b.Property<int>("mark2")
                        .HasColumnType("int");

                    b.Property<int>("mark3")
                        .HasColumnType("int");

                    b.Property<int>("mark4")
                        .HasColumnType("int");

                    b.Property<int>("mark5")
                        .HasColumnType("int");

                    b.Property<int>("mark6")
                        .HasColumnType("int");

                    b.Property<int>("mark7")
                        .HasColumnType("int");

                    b.Property<int>("mark8")
                        .HasColumnType("int");

                    b.Property<string>("semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("session")
                        .HasColumnType("int");

                    b.Property<int>("studentid")
                        .HasColumnType("int");

                    b.Property<int>("subject1")
                        .HasColumnType("int");

                    b.Property<int>("subject2")
                        .HasColumnType("int");

                    b.Property<int>("subject3")
                        .HasColumnType("int");

                    b.Property<int>("subject4")
                        .HasColumnType("int");

                    b.Property<int>("subject5")
                        .HasColumnType("int");

                    b.Property<int>("subject6")
                        .HasColumnType("int");

                    b.Property<int>("subject7")
                        .HasColumnType("int");

                    b.Property<int>("subject8")
                        .HasColumnType("int");

                    b.HasKey("hudao");

                    b.ToTable("StudentNumberSheets");
                });

            modelBuilder.Entity("rajiunschool.Models.subjectlist", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("dept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("instructor")
                        .HasColumnType("int");

                    b.Property<string>("semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subjectname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("takaperclass")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("SubjectLists");
                });

            modelBuilder.Entity("rajiunschool.Models.subjectrequest", b =>
                {
                    b.Property<int>("hudao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hudao"));

                    b.Property<int>("subjectid")
                        .HasColumnType("int");

                    b.Property<int>("teacherid")
                        .HasColumnType("int");

                    b.HasKey("hudao");

                    b.ToTable("SubjectRequests");
                });

            modelBuilder.Entity("rajiunschool.Models.teachercourseview", b =>
                {
                    b.Property<int>("hudao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hudao"));

                    b.Property<int>("classtaken")
                        .HasColumnType("int");

                    b.Property<string>("dept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("session")
                        .HasColumnType("int");

                    b.Property<int>("teacher")
                        .HasColumnType("int");

                    b.HasKey("hudao");

                    b.ToTable("TeacherCourseViews");
                });

            modelBuilder.Entity("rajiunschool.Models.teacherevaluation", b =>
                {
                    b.Property<int>("hudao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hudao"));

                    b.Property<string>("dept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("subjectid")
                        .HasColumnType("int");

                    b.Property<int>("teacherid")
                        .HasColumnType("int");

                    b.HasKey("hudao");

                    b.ToTable("Teacherevaluations");
                });

            modelBuilder.Entity("rajiunschool.Models.users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
